#ifndef VECCORE_CONFIG_H
#define VECCORE_CONFIG_H

#define VECCORE_VERSION_MAJOR 1
#define VECCORE_VERSION_MINOR 1
#define VECCORE_VERSION_PATCH 1

#define VECCORE_VERSION "1"

//#cmakedefine VECCORE_ENABLE_CUDA
//#cmakedefine VECCORE_ENABLE_VC
//#cmakedefine VECCORE_ENABLE_UMESIMD

#endif
